// Seed data scraped from https://jackson.yale.edu/about/meet-us/grad-students/overview/
// Broad tags were normalized from each student's narrative bio.

const POLICY_TAGS = [
  "AI",
  "Climate",
  "Economics",
  "Energy",
  "Finance",
  "Foreign Policy",
  "Health",
  "Human Rights",
  "International Development",
  "Peacebuilding",
  "Politics",
  "Security",
  "Social Policy",
  "Technology Policy",
  "Urban Policy",
];

const REGION_TAGS = [
  "North America",
  "Latin America",
  "Europe",
  "MENA",
  "Sub-Saharan Africa",
  "South Asia",
  "Central Asia",
  "East Asia",
  "Southeast Asia",
  "Oceania",
  "Global South",
];

const STUDENTS = [
  {
    slug: "hekmat-aboukhater",
    whatsapp: "+16179010441",
    summer: "Research fellow at the Quincy Institute for Responsible Statecraft.",
    linkedin: "https://www.linkedin.com/in/hekmataboukhater/",
    email: "hekmat.aboukhater@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Hekmat-Aboukhater-1786595802.jpg",
    name: "Hekmat Aboukhater",
    program: "MPP, Class of 2027",
    policy: ["Foreign Policy", "International Development", "Economics", "Peacebuilding"],
    regions: ["MENA", "Europe", "North America"],
    specifics: ["foreign policy", "international economics", "multinational institutions", "development"],
    blurb: "Foreign policy researcher from Aleppo, Syria, who used to work at the Quincy Institute, the UN Department of Peacebuilding and Political Affairs, and Young Voices Debates; focused on international economics and multinational institutions.",
  },
  {
    slug: "alex-bare",
    whatsapp: "+13522171867",
    summer: "Political and conflict analysis intern with the UN in Dushanbe, Tajikistan, supporting conflict prevention and post-conflict social cohesion.",
    linkedin: "https://www.linkedin.com/in/alex-bare/",
    email: "alex.bare@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Alex-Bare-1786595795-2.jpg",
    name: "Alex Bare",
    program: "MPP, Class of 2027",
    policy: ["Security", "Human Rights", "Foreign Policy", "Peacebuilding"],
    regions: ["Latin America", "Europe", "MENA", "Central Asia"],
    specifics: ["armed conflict resolution", "illicit economies", "human rights", "U.S. foreign policy"],
    blurb: "Conflict and human rights researcher from Iowa who used to work at the Washington Office on Latin America, Foreign Policy for America's NextGen Initiative, and as a Fulbright in Colombia; focused on armed conflict resolution and illicit economies in Colombia, Cuba, and Venezuela.",
  },
  {
    slug: "maya-berlinger",
    whatsapp: "+19144868506",
    summer: "Investment team intern at Anzana Electric Group in Nairobi, supporting hydropower projects across East, Central, and Southern Africa.",
    linkedin: "https://www.linkedin.com/in/mayaberlinger/",
    email: "maya.berlinger@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Maya-Berlinger-1786595809-2.jpg",
    name: "Maya Berlinger",
    program: "MPP, Class of 2027",
    policy: ["Climate", "Energy", "Finance"],
    regions: ["Global South", "Sub-Saharan Africa"],
    specifics: ["energy access", "renewable energy deployment", "climate finance", "innovative financing mechanisms"],
    blurb: "Climate and energy specialist who used to work at Y Analytics, McKinsey, and the World Economic Forum; focused on energy access and climate finance across the Global South.",
  },
  {
    slug: "bernard-birikorang",
    whatsapp: "+12036064486",
    summer: "Bekenstein Climate Intern at the Clean Energy States Alliance, supporting its Virtual Power Plant Acceleration Initiative.",
    linkedin: "https://www.linkedin.com/in/bernard-birikorang/",
    email: "ben.birikorang@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Bernard-Birikorang-1786595804.jpg",
    name: "Bernard Birikorang",
    program: "MPP/MEM, Class of 2027",
    policy: ["Climate", "Energy"],
    regions: ["Sub-Saharan Africa", "North America"],
    specifics: ["climate governance", "climate communication", "behavioral science in adaptation", "climate resilience"],
    blurb: "Climate practitioner from Effiakuma, Ghana, who co-founded EcoClimate Vision and led Enactus UMaT; focused on climate governance and resilience in underserved communities.",
  },
  {
    slug: "kevin-chen",
    electives: "AI, Emerging Technology, and National Power; Managing the Clean Energy Transition; Spies, Cyber, and Statecraft; Stablecoins, Distributed Ledger Technology, and Trade.",
    groups: "Yale Journal of International Affairs; Yale AI Policy Forum; Digital Ethics Center Policy Fellow; Teaching Fellow for *Intelligence, Espionage, and American Foreign Policy*.",
    whatsapp: "+18652350680",
    summer: "Research fellow at the Centre for the Governance of AI (GovAI) in London, evaluating geopolitical bias in large language models with the UK Prime Minister's AI office.",
    linkedin: "https://www.linkedin.com/in/kevinchenpage/",
    email: "kevin.chen.kc2593@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Kevin-Chen-1786595803-1.jpg",
    name: "Kevin Chen",
    program: "MPP, Class of 2027",
    policy: ["AI", "Technology Policy", "Security"],
    regions: ["East Asia", "North America", "Europe"],
    specifics: ["epistemic risk in AI", "countering disinformation", "AI governance", "cybersecurity", "Taiwan's digital sovereignty"],
    blurb: "Technology policy researcher who used to work as a data scientist in U.S. intelligence and national security; focused on epistemic risk in AI, countering disinformation, cybersecurity, and making AI work for everyone.",
  },
  {
    slug: "anthony-costanzo",
    whatsapp: "+15038080965",
    summer: "Business development and market research with Forward Horizon Group in Kyiv, Ukraine, plus field research on technology transfer among frontline states.",
    linkedin: "https://www.linkedin.com/in/asc2237/",
    email: "anthony.costanzo@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Anthony-Costanzo-1786595818-1.jpg",
    name: "Anthony Costanzo",
    program: "MPP, Class of 2027",
    policy: ["Technology Policy", "AI", "Security"],
    regions: ["East Asia", "Europe"],
    specifics: ["U.S.–China competition", "naval warfare", "machine learning in intelligence analysis", "crisis decision-making", "Mandarin study in Taiwan"],
    blurb: "Veteran from the United States who used to serve in the Marine Corps, worked at the Institute for Global Politics, the Saltzman Institute, and the Cambridge Security Initiative, and co-founded the Samuel B. Griffith Foundation; focused on U.S.–China competition and machine learning in intelligence analysis.",
  },
  {
    slug: "sarah-coughlin",
    whatsapp: "+19786542412",
    summer: "",
    linkedin: "https://www.linkedin.com/in/sarah-coughlin-abb6093a7/",
    email: "sarah.coughlin@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Sarah-Coughlin-1786595810-2.jpg",
    name: "Sarah Coughlin",
    program: "MPP/MBA, Class of 2028",
    policy: ["Climate", "International Development"],
    regions: ["Global South"],
    specifics: ["climate resilience", "food systems equity", "agricultural development", "digital services for smallholder farmers"],
    blurb: "Development researcher who used to work at J-PAL, a small-scale organic farm, and the YMCA of Greater Boston; focused on climate resilience and food systems for smallholder farmers.",
  },
  {
    slug: "lisa-de-rafols",
    whatsapp: "+17753760111",
    summer: "Intern at the EBRD in London on the Policy, Strategy, and Delivery team, supporting its expansion into sub-Saharan Africa.",
    linkedin: "https://www.linkedin.com/in/lisaderafols/",
    email: "lisa.derafols@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Lisa-de-Rafols-1786595812-1.jpg",
    name: "Lisa de Ràfols",
    program: "MPP, Class of 2027",
    policy: ["International Development", "Foreign Policy", "Politics", "Peacebuilding", "Social Policy"],
    regions: ["Latin America", "Sub-Saharan Africa", "Europe"],
    specifics: ["peacebuilding", "political economy", "social protection", "development and diplomacy"],
    blurb: "Development researcher from Nevada who used to work at J-PAL, the City of Los Angeles, a Nevada political campaign, and as a Fulbright in Colombia; focused on peacebuilding and political economy in Latin America.",
  },
  {
    slug: "alejandro-dominguez",
    whatsapp: "+12035897840",
    summer: "AI policy intern at the Tony Blair Institute for Global Change in Washington, D.C., working with governments across Latin America and the Caribbean.",
    linkedin: "https://www.linkedin.com/in/aledomcris/",
    email: "alejandro.dominguezcristerna@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Alejandro-Dominguez-1786595796-2.jpg",
    name: "Alejandro Domínguez",
    program: "MPP, Class of 2027",
    policy: ["Technology Policy", "AI", "Politics", "Urban Policy"],
    regions: ["Latin America"],
    specifics: ["technology and democratic institutions", "anti-corruption", "urban mobility", "machine learning in policy analysis"],
    blurb: "Public servant from Mexico who used to work in Nuevo León's Ministry of Education and Congress, at UNDP, and at Tecnológico de Monterrey; focused on technology, democratic institutions, and anti-corruption.",
  },
  {
    slug: "sherab-dorji",
    whatsapp: "+97517722727",
    summer: "Supported the Bhutan Trust Fund for Environmental Conservation in Thimphu, strengthening monitoring and evaluation of Green Climate Fund and Adaptation Fund investments.",
    linkedin: "https://www.linkedin.com/in/sherab-dorji/",
    email: "sherab.dorji@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Sherab-Dorji-1786595815-1.jpg",
    name: "Sherab Dorji",
    program: "MPP/MEM, Class of 2027",
    policy: ["Climate", "Energy", "International Development", "Social Policy", "Human Rights", "Finance"],
    regions: ["South Asia", "Global South"],
    specifics: ["ecosystem management", "locally led climate adaptation", "clean energy access", "land restoration"],
    blurb: "Climate and clean energy practitioner from Bhutan who used to work at Evergreen Economics, the Yale Center for Environmental Law and Policy, and as a Global Resilience Partnership fellow; focused on locally led adaptation and land restoration.",
  },
  {
    slug: "vaibhav-dutt",
    whatsapp: "+919899093400",
    summer: "",
    linkedin: "https://www.linkedin.com/in/duttvaibhav/",
    email: "vaibhav.dutt@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Vaibhav-Dutt-1786595816-1.jpg",
    name: "Vaibhav Dutt",
    program: "MPP, Class of 2027",
    policy: ["Urban Policy", "Technology Policy", "Climate", "Human Rights", "Social Policy"],
    regions: ["South Asia", "Sub-Saharan Africa", "Europe"],
    specifics: ["sustainable urban development", "data governance", "digital rights", "service delivery"],
    blurb: "Lawyer from India who used to work at Athena Infonomics, Belongg, and Fields of View, and co-founded a social impact startup; focused on sustainable urban development, data governance, and digital rights.",
  },
  {
    slug: "camden-dyer",
    whatsapp: "+17752215076",
    summer: "Intern with UNDP's Inclusive Growth Team in Bangkok, Thailand.",
    linkedin: "https://www.linkedin.com/in/camden-dyer-56a44a194/",
    email: "camden.dyer@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Camden-Dyer-1786595807-1.jpg",
    name: "Camden Dyer",
    program: "MPP, Class of 2027",
    policy: ["Economics", "International Development", "Social Policy"],
    regions: ["Latin America", "Southeast Asia"],
    specifics: ["political economy", "inclusive economic development", "global labor relations", "unionization"],
    blurb: "Economic development professional from New Orleans who used to serve in the Peace Corps in Costa Rica and worked at the State Department and the U.S. Embassy in Quito; focused on political economy and global labor relations.",
  },
  {
    slug: "bryn-evans",
    whatsapp: "+16043193488",
    summer: "",
    linkedin: "https://www.linkedin.com/in/brynevans/",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Bryn-Evans-1786595721-1.jpg",
    name: "Bryn Evans",
    program: "MPP/MEM, Class of 2027",
    policy: ["Human Rights", "Climate"],
    regions: ["North America"],
    specifics: ["minority rights", "Indigenous rights", "environmental policy", "culturally inclusive policy"],
    blurb: "Environmental policy advocate from Canada who used to work at Ratcliff LLP and the U'mista Kwak'wala Language Revitalization Planning Program; focused on Indigenous rights and culturally inclusive policy on the Pacific Northwest Coast.",
  },
  {
    slug: "gabriel-falk",
    whatsapp: "+16077937365",
    summer: "Blended Finance team intern at the IFC in Washington, D.C., as part of the World Bank Group Pioneers program.",
    linkedin: "https://www.linkedin.com/in/gabriel-falk/",
    email: "gabriel.falk@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Gabriel-Falk-1786595798-1.jpg",
    name: "Gabriel Falk",
    program: "MPP/MBA, Class of 2027",
    policy: ["Finance", "International Development", "AI"],
    regions: ["Sub-Saharan Africa", "Global South"],
    specifics: ["development finance", "blended finance", "AI-assisted investment", "emerging market capital"],
    blurb: "Development finance professional from Ithaca, New York, who used to work on governance programs in West Africa; focused on blended finance and AI-assisted investment.",
  },
  {
    slug: "rafael-gonzalez",
    whatsapp: "+16177553675",
    summer: "Legal group intern at the Center for AI and Digital Policy.",
    linkedin: "https://www.linkedin.com/in/rafael-gonzalez-yalempp/",
    email: "rafael.gonzalez.reg53@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Rafael-Gonzalez-1786595819.jpg",
    name: "Rafael Gonzalez",
    program: "MPP, Class of 2027",
    policy: ["International Development", "Climate", "AI", "Technology Policy"],
    regions: ["North America"],
    specifics: ["agri-food systems", "economic and societal development"],
    blurb: "Development professional from Vancouver, Canada, who used to work at the World Food Programme, the International Atomic Energy Agency, and Boston Consulting Group; focused on agri-food systems and economic development.",
  },
  {
    slug: "liam-graf",
    whatsapp: "+15105025454",
    summer: "",
    linkedin: "https://www.linkedin.com/in/liam-graf-3020791b1/",
    email: "liam.graf@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Liam-Graf-1786595808-2.jpg",
    name: "Liam Graf",
    program: "MPP, Class of 2027",
    policy: ["Technology Policy", "Security", "Foreign Policy"],
    regions: ["Latin America", "North America"],
    specifics: ["emerging technology and national security", "broadband development"],
    blurb: "Technology and security professional from the United States who used to serve in the Peace Corps in Ecuador and worked at CTC Technology and Energy on broadband development; focused on emerging technology and national security.",
  },
  {
    slug: "arunima-gupta",
    whatsapp: "+12034108734",
    summer: "Worked in the CEO's Office at IDinsight in Lusaka, Zambia.",
    linkedin: "https://www.linkedin.com/in/arunima-gupta-2862651a9/",
    email: "arunima.gupta@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Arunima-Gupta-1786595805.jpg",
    name: "Arunima Gupta",
    program: "MPP, Class of 2027",
    policy: ["Climate", "Social Policy", "International Development"],
    regions: ["South Asia", "Sub-Saharan Africa"],
    specifics: ["ESG strategy", "behavioral public policy", "welfare delivery systems", "public-sector innovation"],
    blurb: "Policy consultant from India who used to work at Bain & Company and Josh Talks, founded Flipitt, and co-founded Colleges for Climate Action; focused on climate, ESG strategy, and welfare delivery.",
  },
  {
    slug: "trisha-gupta",
    whatsapp: "+12815123205",
    summer: "",
    linkedin: "https://www.linkedin.com/in/trisha-gupta-/",
    email: "trisha.gupta@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Trisha-Gupta-1786595817-1.jpg",
    name: "Trisha Gupta",
    program: "MPP, Class of 2027",
    policy: ["Climate", "International Development", "Finance"],
    regions: [],
    specifics: ["climate resilience", "sustainable investing", "global environmental governance", "earth science"],
    blurb: "Climate specialist who used to work at L.E.K. Consulting and NASA Langley; focused on climate resilience, sustainable investing, and global environmental governance.",
  },
  {
    slug: "ameya-hadap",
    whatsapp: "+16099039906",
    summer: "Research and editorial fellow at Heatmap News in New York.",
    linkedin: "https://www.linkedin.com/in/ameya-hadap-7a082214a/",
    email: "ameya.hadap@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Ameya-Hadap-1786595797-2.jpg",
    name: "Ameya Hadap",
    program: "MPP, Class of 2027",
    policy: ["Energy", "Climate", "Finance", "Security"],
    regions: ["North America"],
    specifics: ["energy transition", "utility regulation", "nuclear energy policy", "cybersecurity", "energy affordability"],
    blurb: "Energy policy analyst from New Jersey who used to work at PowerLines, the World Economic Forum, and the Atlantic Council; focused on the energy transition, utility regulation, and climate finance.",
  },
  {
    slug: "arshia-haque",
    whatsapp: "+14753726431",
    summer: "Built cost-effectiveness methodology for poverty graduation programs at Better Futures Guide, an evaluator guiding donors to high-impact livelihoods charities.",
    linkedin: "https://www.linkedin.com/in/arshia-haque/",
    email: "arshia.haque@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Arshia-Haque-1786595799-1.jpg",
    name: "Arshia Haque",
    program: "MPP, Class of 2027",
    policy: ["International Development", "Finance", "Climate", "Economics"],
    regions: ["South Asia"],
    specifics: ["inclusive finance", "climate adaptation", "disaster response", "digital payments access"],
    blurb: "Development practitioner from Bangladesh who used to work at the World Bank and co-founded a youth-led platform in Bangladesh; focused on inclusive finance, climate adaptation, and disaster response.",
  },
  {
    slug: "ryan-hawkins",
    whatsapp: "+61423057909",
    summer: "",
    linkedin: "https://www.linkedin.com/in/ryan-hawkins-5841b0376/",
    email: "ryan.hawkins@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Ryan-Hawkins-1786595814-1.jpg",
    name: "Ryan Hawkins",
    program: "MPP, Class of 2027",
    policy: ["Security"],
    regions: ["Oceania", "North America"],
    specifics: ["national security", "defense policy", "U.S.–Australia alliance"],
    blurb: "Defense policy specialist from Australia who used to work in the Office of the Deputy Prime Minister and Minister for Defense, the Office of National Intelligence, and the Department of the Prime Minister and Cabinet; focused on national security and the U.S.–Australia alliance.",
  },
  {
    slug: "axel-herrera-ramos",
    whatsapp: "+19196991524",
    summer: "",
    linkedin: "https://www.linkedin.com/in/axel-herrera-ramos/",
    email: "axel.herreraramos@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Axel-Herrera-Ramos-1786595804-1.jpg",
    name: "Axel Herrera Ramos",
    program: "MPP/MBA, Class of 2028",
    policy: ["Climate", "Energy", "Human Rights", "Politics"],
    regions: ["North America", "Latin America"],
    specifics: ["climate displacement", "environmental justice", "immigrant justice", "civic engagement"],
    blurb: "Community organizer born in Honduras who used to work at Mi Familia Vota and served on Durham's Participatory Budgeting Steering Committee and the Durham Public Schools Foundation board; focused on climate, environmental justice, and immigrant justice.",
  },
  {
    slug: "jason-hug",
    whatsapp: "+14197990507",
    summer: "",
    linkedin: "https://www.linkedin.com/in/jasonhug/",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Jason-Hug-1786595617-1.jpg",
    name: "Jason Hug",
    program: "MPP/JD, Class of 2027",
    policy: ["Security", "Foreign Policy", "Politics"],
    regions: ["Europe", "East Asia", "South Asia"],
    specifics: ["law of armed conflict", "transnational security threats", "U.S.–China relations", "democratic backsliding"],
    blurb: "Army intelligence officer who used to serve across Germany, Finland, Romania, and Afghanistan and interned in the U.S. House of Representatives; focused on the law of armed conflict and democratic backsliding.",
  },
  {
    slug: "priavi-joshi",
    whatsapp: "+918527448100",
    summer: "",
    linkedin: "https://www.linkedin.com/in/priavi-joshi-959b783a8/",
    email: "priavi.joshi@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Priavi-Joshi-1786595818-1.jpg",
    name: "Priavi Joshi",
    program: "MPP, Class of 2027",
    policy: ["Politics", "International Development", "Social Policy", "Human Rights"],
    regions: ["South Asia"],
    specifics: ["social movements", "participatory democratic governance", "gender and intersectionality", "community-centered development"],
    blurb: "Development researcher from India who used to work at IDinsight and the Trivedi Centre for Political Data; focused on social movements and participatory governance.",
  },
  {
    slug: "colby-ko",
    whatsapp: "+16173010929",
    summer: "Joined the U.S. Department of Energy's ARPA-E to research how to accelerate the nuclear power industry.",
    groups: "Leader of the veterans club; cross-country skiing, golf, and tennis.",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Colby-Ko-1786854931-2.jpg",
    name: "Colby Ko",
    program: "MPP/MBA, Class of 2027",
    policy: ["Energy", "Security", "Foreign Policy", "Technology Policy"],
    regions: ["East Asia", "North America"],
    specifics: ["nuclear energy", "emerging technologies", "business, policy, and engineering", "Korean Peninsula security"],
    blurb: "Navy veteran and U.S. Naval Academy graduate who used to operate nuclear reactors aboard U.S. submarines and worked at the United Nations Command in South Korea enforcing the Korean Armistice along the DMZ; focused on the intersection of business, policy, and engineering.",
  },
  {
    slug: "seiyoon-ko",
    whatsapp: "+821027424329",
    summer: "Privacy and Data team at the Center for Democracy and Technology in Washington, D.C., working on consumer privacy and AI-driven advertising.",
    linkedin: "https://www.linkedin.com/in/seiyoonko/",
    email: "seiyoon.ko@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Seiyoon-Ko-1786595816-1.jpg",
    name: "Seiyoon Ko",
    program: "MPP, Class of 2027",
    policy: ["AI", "Technology Policy"],
    regions: ["East Asia", "North America"],
    specifics: ["AI governance", "platform regulation", "society and algorithms"],
    blurb: "Technology policy researcher from Seoul, South Korea, who used to work at LY Corporation, NCSOFT, TikTok, and Korea's Ministry of Science and ICT; focused on AI governance and platform regulation.",
  },
  {
    slug: "andrzej-korlacki",
    whatsapp: "+14028753196",
    summer: "",
    linkedin: "https://www.linkedin.com/in/andrzej-korlacki-67919b338/",
    email: "andrzej.korlacki@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Andrzej-Korlacki-1786595797.jpg",
    name: "Andrzej Korlacki",
    program: "MPP, Class of 2027",
    policy: ["Security"],
    regions: [],
    specifics: [],
    blurb: "Military officer who used to serve in the U.S. Marine Corps and worked at the Naval Academy Preparatory School.",
    inferred: true,
  },
  {
    slug: "avia-liberman",
    whatsapp: "+972542512299",
    summer: "Junior fellow in the Atlantic Council's Middle East Programs.",
    linkedin: "https://www.linkedin.com/in/avia-liberman/",
    email: "avia.liberman@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Avia-Liberman-1786595800.jpg",
    name: "Avia Liberman",
    program: "MPP, Class of 2027",
    policy: ["Economics", "International Development", "Peacebuilding", "Human Rights"],
    regions: ["MENA"],
    specifics: ["fiscal policy", "labor market reform", "trade policy", "post-conflict economic design"],
    blurb: "Economist who used to work at Israel's Ministry of Finance and the OECD and founded Itutim; focused on fiscal policy, labor market reform, and post-conflict economic design in Israel and Palestine.",
  },
  {
    slug: "metasebiya-ayele-mamo",
    whatsapp: "+12036764840",
    summer: "",
    linkedin: "https://www.linkedin.com/in/metasebiya-mamo/",
    email: "metasebiya.mamo@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Metasebiya-Ayele-Mamo-1786595809-1.jpg",
    name: "Metasebiya Ayele Mamo",
    program: "MPP, Class of 2027",
    policy: ["Health"],
    regions: ["Sub-Saharan Africa"],
    specifics: ["global health security", "health equity and access", "pandemic response", "public health systems"],
    blurb: "Public health professional born in Ethiopia who used to work at GIZ and Africa CDC and was a Princeton in Africa fellow with the Baylor International Pediatric AIDS Initiative; focused on health security and equitable access.",
  },
  {
    slug: "nicola-mcpherson",
    whatsapp: "+61407711694",
    electives: "Interpersonal and Group Dynamics, Renewable Energy Project Finance, and The Diploma Divide in Western Politics.",
    groups: "Deitz Global Affairs and the Environment Student Fellow.",
    summer: "Joined the international team at the Center for Climate and Energy Solutions (C2ES) in Washington, D.C., working on international climate policy.",
    linkedin: "https://www.linkedin.com/in/nicola-m-82abba10a/",
    email: "nicola.mcpherson@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Nicola-McPherson-1786595813.jpg",
    name: "Nicola McPherson",
    program: "MPP, Class of 2027",
    policy: ["Climate", "Energy", "Economics"],
    regions: ["Oceania"],
    specifics: ["energy sector emissions", "economic incentives for climate action", "public institutions"],
    blurb: "Climate policy specialist from Australia who used to work in the Department of the Prime Minister and Cabinet and the Department of Climate Change, Energy, the Environment and Water, and represented Australia at the IPCC; focused on energy emissions and economic incentives for climate action.",
  },
  {
    slug: "paige-miles",
    whatsapp: "+14054204844",
    summer: "",
    linkedin: "https://www.linkedin.com/in/paige-miles-m204218/",
    email: "paige.miles@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Paige-Miles-1786595811.jpg",
    name: "Paige Miles",
    program: "MPP, Class of 2027",
    policy: ["International Development", "Economics", "Social Policy"],
    regions: ["South Asia"],
    specifics: ["development economics", "gender equity", "early childhood development"],
    blurb: "Navy veteran from Oklahoma who used to serve aboard the USS Ohio and worked at the Oklahoma Medical Research Foundation and the Joint Allies Research Program; focused on development economics, gender equity, and early childhood development.",
  },
  {
    slug: "peter-nelson",
    summer: "",
    linkedin: "https://www.linkedin.com/in/peter-nelson-1991vt/",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Peter-Nelson-1786595636-1.jpg",
    name: "Peter Nelson",
    program: "MPP/JD",
    policy: ["Security", "Politics"],
    regions: ["MENA", "North America"],
    specifics: ["national security", "political advocacy", "election law"],
    blurb: "Marine Corps veteran from Vermont who used to serve in Iraq and worked at the National Geospatial-Intelligence Agency, in management consulting, and on political campaigns; focused on national security, political advocacy, and election law.",
  },
  {
    slug: "jonas-nepozitek",
    whatsapp: "+12038096230",
    electives: "Macroeconomics and Security Policy, Defense Innovation in the US.",
    groups: "Yale Journal of International Affairs; Blue Center Research Assistant; Teaching Fellow for *Intelligence, Espionage, and American Foreign Policy*.",
    summer: "Business development and market research with Forward Horizon Group in Kyiv, Ukraine, plus field research on technology transfer among frontline states.",
    linkedin: "https://www.linkedin.com/in/jonas-nepozitek/",
    email: "jonas.nepozitek@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Jonas-Nepozitek-1786595801-1.jpg",
    name: "Jonáš Nepožitek",
    program: "MPP, Class of 2027",
    policy: ["AI", "Economics", "Security", "Technology Policy"],
    regions: ["North America", "Europe"],
    specifics: ["European security", "defense-industrial policy", "dual-use emerging tech", "evidence-based policymaking"],
    blurb: "Ex-civil servant from the Czech Republic who worked at the Czech Office of the Government, the Czech Ministry of Finance, and London Politica; focuses on European security, defense-industrial policy, and dual-use emerging tech.",
  },
  {
    slug: "lena-olszewska",
    whatsapp: "+919810207163",
    electives: "Observing Earth from Space; Earth System Science for Public Policy; Inclusive Economic Development.",
    groups: "Environmental Data Science at Yale (EDSY).",
    summer: "Machine learning intern with Atlas AI in Nairobi, Kenya, building satellite-imagery models to predict public health outcomes like vaccination rates and anemia prevalence.",
    linkedin: "https://www.linkedin.com/in/lena-olszewska-83727a15a/",
    email: "lena.olszewska@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Lena-Olszewska-1786595812-2.jpg",
    name: "Lena Olszewska",
    program: "MPP, Class of 2027",
    policy: ["Climate", "International Development", "Social Policy", "Health", "AI"],
    regions: ["South Asia", "Europe", "Global South", "Sub-Saharan Africa"],
    specifics: ["climate mitigation and social outcomes", "data science", "environmental modelling", "remote sensing and satellite imagery", "health", "gender equity"],
    blurb: "Development professional with Polish roots who used to work at IDinsight, Giving Green, Plan International's EU office, and the British Embassy in Warsaw; focused on climate mitigation and its social outcomes in India.",
  },
  {
    slug: "hudson-ozello",
    whatsapp: "+16146709003",
    electives: "Impact Measurement and Financial Reporting in the Social Sector; Public Health Entrepreneurship and Intrapreneurship.",
    groups: "Social Impact Initiative; intramural volleyball; Jackson Salon.",
    summer: "Business strategy intern at the Bamboo Institute in Timor-Leste, back with his former Peace Corps community.",
    linkedin: "https://www.linkedin.com/in/hudsonozello/",
    email: "hudson.ozello@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Hudson-Ozello-1786595807-1.jpg",
    name: "Hudson Ozello",
    program: "MPP, Class of 2027",
    policy: ["International Development"],
    regions: ["Global South", "Southeast Asia"],
    specifics: ["social enterprise", "poverty alleviation", "non-profit consulting", "public-private partnerships"],
    blurb: "Social enterprise professional with six years of experience in management consulting leading technical systems implementations alongside Peace Corps experience working with a government-funded social enterprise to improve marketing and tourism strategy; focused on social enterprise, non-profit consulting, and poverty alleviation.",
  },
  {
    slug: "federico-perez",
    whatsapp: "+573054073434",
    summer: "Summer consultant at Greenwood Energy; supported the Concordia Amazonas Initiative convening in Leticia, Colombia.",
    linkedin: "https://www.linkedin.com/in/fedeperez1/",
    email: "federico.perez@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Federico-Perez-1786595803.jpg",
    name: "Federico Pérez",
    program: "MPP/MEM, Class of 2027",
    policy: ["Climate", "Energy"],
    regions: ["Latin America"],
    specifics: ["forest conservation", "climate resilience", "supply chain management"],
    blurb: "Conservation professional from Colombia who founded Selvitas, used to work at the International Trade Centre, and serves on the Latin America board of the Prince Albert II of Monaco Foundation; focused on forest conservation and climate resilience.",
  },
  {
    slug: "pankhuri-prasad",
    whatsapp: "+18582579063",
    summer: "Intern at the EBRD in London.",
    linkedin: "https://www.linkedin.com/in/pankhuriprasad/",
    email: "pankhuri.prasad@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Pankhuri-Prasad-1786595811-1.jpg",
    name: "Pankhuri Prasad",
    program: "MPP, Class of 2027",
    policy: ["Urban Policy", "Economics", "International Development", "Finance"],
    regions: ["South Asia", "Sub-Saharan Africa", "MENA"],
    specifics: ["urban economic policy", "labor market policy", "cash transfer programs", "economic diversification"],
    blurb: "Economic policy researcher who used to work at Mathematica, Harvard's Growth Lab, the Centre for Effective Governance of Indian States, and the U.S. State Department; focused on urban economic policy and labor markets in South Asia.",
  },
  {
    slug: "austin-rose",
    summer: "",
    linkedin: "https://www.linkedin.com/in/austin-rose-20a67a236/",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Austin-Rose-1786595624-2.jpg",
    name: "Austin Rose",
    program: "MPP/JD, Class of 2027",
    policy: ["Urban Policy", "Economics"],
    regions: ["East Asia", "North America"],
    specifics: ["zoning regulations", "occupational licensing", "municipal water quality", "local government"],
    blurb: "Logistics officer who used to serve in the Marine Corps in Okinawa, Japan; focused on zoning, occupational licensing, and local government.",
  },
  {
    slug: "ana-saenz-de-tejada",
    whatsapp: "+50257238314",
    summer: "Worked at The Rockefeller Foundation in New York on the Strategic Learning and Impact team, including an AI deployment strategy for monitoring, evaluation, and learning.",
    linkedin: "https://www.linkedin.com/in/anasaenzdetejada/",
    email: "ana.saenzdetejadagarces@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Ana-Saenz-de-Tejada-1786595795.jpg",
    name: "Ana Sáenz de Tejada",
    program: "MPP, Class of 2027",
    policy: ["International Development", "AI", "Social Policy", "Human Rights"],
    regions: ["Latin America"],
    specifics: ["program evaluation", "evidence-based social interventions", "AI ethics in public policy"],
    blurb: "Program evaluator from Guatemala who used to work with UN Women and UNHCR; focused on evidence-based social interventions and AI ethics in policy.",
  },
  {
    slug: "tom-steer",
    noJacksonBio: true,
    linkedin: "https://www.linkedin.com/in/tom-steer-a26035384/",
    whatsapp: "+447804983566",
    email: "tom.steer@yale.edu",
    summer: "Fellow at the Institute for AI Policy and Strategy (IAPS).",
    electives: "Democracy and Distribution; Inclusive Economic Development in South Africa.",
    groups: "Jackson Soccer; Teaching Fellow for *Applied Methods of Analysis* and *Economics for Global Affairs*.",
    photo: "photos/tom-steer.jpg",
    name: "Tom Steer",
    program: "MPP",
    policy: ["AI", "Security", "Economics", "International Development"],
    regions: ["Europe"],
    specifics: ["frontier AI security", "international security", "inclusive economic development", "technological change and inequality"],
    blurb: "Security and economics professional from the UK who used to work for the UK government for six years, including advising the UK AI Security Institute on testing frontier AI models against misuse; focused on inclusive economic development in an era of rapid technological change and geopolitical competition.",
  },
  {
    slug: "michael-thompson",
    whatsapp: "+12034196562",
    summer: "Summer investment professional at Allied Climate Partners in New York.",
    linkedin: "https://www.linkedin.com/in/michael-thompson-85bb3611a/",
    email: "michael.thompson.mkt44@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Michael-Thompson-1786595814.jpg",
    name: "Michael Thompson",
    program: "MPP/MBA, Class of 2028",
    policy: ["Climate", "International Development", "Finance"],
    regions: ["Sub-Saharan Africa", "Europe"],
    specifics: ["climate innovation", "impact investing", "frontier markets", "systems investing"],
    blurb: "Impact investor from Ghana with eight years across agriculture, renewable energy, and financial services who used to work at Blue Haven Initiative; focused on climate innovation and frontier markets.",
  },
  {
    slug: "chang-tu",
    whatsapp: "+12035076081",
    electives: "Data Exploration and Analysis; Persuasive Writing for Policymakers; Market Failures in Developing Countries; Stablecoins, Distributed Ledger Technology, and Trade.",
    groups: "AAPIA Vice President.",
    summer: "Intern in the World Bank's Development Economics Vice Presidency, researching private capital mobilization.",
    linkedin: "https://www.linkedin.com/in/tuchang/",
    email: "chang.tu@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Chang-Tu-1786595801.jpg",
    name: "Chang Tu",
    program: "MPP, Class of 2027",
    policy: ["Finance", "Economics", "International Development"],
    regions: ["Southeast Asia"],
    specifics: ["financial stability", "inclusive financial systems", "emerging economies"],
    blurb: "Finance professional from Singapore who used to work at the Monetary Authority of Singapore; focused on financial stability and inclusive financial systems in Southeast Asia.",
  },
  {
    slug: "cheney-wen",
    whatsapp: "+886916221915",
    summer: "Project on deepening Indo-Pacific security cooperation at Taiwan's National Security Council.",
    linkedin: "https://www.linkedin.com/in/cheney-chengjhe-wen/",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Cheney-Wen-1786595735-1.jpg",
    name: "Cheney Wen",
    program: "MPP/JD, Class of 2028",
    policy: ["Security", "Foreign Policy"],
    regions: ["East Asia", "North America"],
    specifics: ["Taiwan–U.S.–China relations", "American grand strategy", "national security law", "international law"],
    blurb: "Law student from Taiwan who used to work on President Lai Ching-te's presidential campaign and at the Legislative Yuan; focused on Taiwan–U.S.–China relations and national security law.",
  },
  {
    slug: "isaiah-williams",
    whatsapp: "+19143123439",
    summer: "Policy intern at CEBRI in Rio de Janeiro, working with its North America and Environment and Climate programs.",
    linkedin: "https://www.linkedin.com/in/isaiahawilliams/",
    email: "isaiah.williams@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Isaiah-Williams-1786595806-1.jpg",
    name: "Isaiah Williams",
    program: "MPP, Class of 2027",
    policy: ["Climate", "International Development", "Foreign Policy"],
    regions: ["Latin America", "North America"],
    specifics: ["regenerative agriculture", "environmental justice", "food system resilience", "nature-based solutions"],
    blurb: "Engineer from the United States who used to work in infrastructure engineering consulting and served in the Peace Corps in Panama; focused on regenerative agriculture and environmental justice.",
  },
];
