// Seed data scraped from https://jackson.yale.edu/about/meet-us/grad-students/overview/
// Broad tags were normalized from each student's narrative bio.

const POLICY_TAGS = [
  "AI",
  "Climate",
  "Economics",
  "Energy",
  "Finance",
  "Foreign Policy",
  "Health",
  "Human Rights",
  "International Development",
  "Politics",
  "Security",
  "Social Policy",
  "Technology Policy",
  "Urban Policy",
];

const REGION_TAGS = [
  "North America",
  "Latin America",
  "Europe",
  "MENA",
  "Sub-Saharan Africa",
  "South Asia",
  "East Asia",
  "Southeast Asia",
  "Oceania",
  "Global South",
];

const STUDENTS = [
  {
    slug: "hekmat-aboukhater",
    email: "hekmat.aboukhater@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Hekmat-Aboukhater-1786595802.jpg",
    name: "Hekmat Aboukhater",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Foreign Policy", "International Development", "Economics"],
    regions: ["MENA", "Europe", "North America"],
    specifics: ["foreign policy", "international economics", "multinational institutions", "development"],
    blurb: "Foreign policy researcher who used to work at the Quincy Institute and the UN, from Aleppo, Syria; focused on international economics and multinational institutions.",
  },
  {
    slug: "alex-bare",
    email: "alex.bare@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Alex-Bare-1786595795-2.jpg",
    name: "Alex Bare",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Security", "Human Rights", "Foreign Policy"],
    regions: ["Latin America", "Europe", "MENA"],
    specifics: ["armed conflict resolution", "illicit economies", "human rights", "U.S. foreign policy"],
    blurb: "Conflict and human rights researcher from Iowa; focused on armed conflict resolution and illicit economies in Colombia, Cuba, and Venezuela.",
  },
  {
    slug: "maya-berlinger",
    email: "maya.berlinger@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Maya-Berlinger-1786595809-2.jpg",
    name: "Maya Berlinger",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Climate", "Energy", "Finance"],
    regions: ["Global South"],
    specifics: ["energy access", "renewable energy deployment", "climate finance", "innovative financing mechanisms"],
    blurb: "Climate and energy specialist; focused on energy access and climate finance across the Global South.",
  },
  {
    slug: "bernard-birikorang",
    email: "ben.birikorang@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Bernard-Birikorang-1786595804.jpg",
    name: "Bernard Birikorang",
    program: "MPP in Global Affairs, Class of 2027 (joint MEM, Yale School of the Environment)",
    policy: ["Climate"],
    regions: ["Sub-Saharan Africa"],
    specifics: ["climate governance", "climate communication", "behavioral science in adaptation", "climate resilience"],
    blurb: "Climate practitioner who has worked across 50+ countries, from Effiakuma, Ghana; focused on climate governance and resilience in underserved communities.",
  },
  {
    slug: "kevin-chen",
    email: "kevin.chen.kc2593@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Kevin-Chen-1786595803-1.jpg",
    name: "Kevin Chen",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["AI", "Technology Policy", "Security"],
    regions: ["East Asia", "North America"],
    specifics: ["AI influence operations", "cybersecurity", "technology governance", "generative AI risks"],
    blurb: "Taiwanese-American technology policy researcher; focused on AI influence operations, cybersecurity, and Taiwan's digital sovereignty.",
  },
  {
    slug: "anthony-costanzo",
    email: "anthony.costanzo@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Anthony-Costanzo-1786595818-1.jpg",
    name: "Anthony Costanzo",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Technology Policy", "AI", "Security"],
    regions: ["East Asia"],
    specifics: ["U.S.–China competition", "naval warfare", "machine learning in intelligence analysis", "crisis decision-making"],
    blurb: "Marine Corps veteran who studied Mandarin in Taiwan, from the United States; focused on U.S.–China competition and machine learning in intelligence analysis.",
  },
  {
    slug: "sarah-coughlin",
    email: "sarah.coughlin@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Sarah-Coughlin-1786595810-2.jpg",
    name: "Sarah Coughlin",
    program: "MPP in Global Affairs (joint MBA), Class of 2028",
    policy: ["Climate", "International Development"],
    regions: ["Global South"],
    specifics: ["climate resilience", "food systems equity", "agricultural development", "digital services for smallholder farmers"],
    blurb: "Development researcher who used to work at J-PAL; focused on climate resilience and food systems for smallholder farmers.",
  },
  {
    slug: "lisa-de-rafols",
    email: "lisa.derafols@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Lisa-de-Rafols-1786595812-1.jpg",
    name: "Lisa de Ràfols",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["International Development", "Foreign Policy", "Politics", "Climate"],
    regions: ["Latin America"],
    specifics: ["peacebuilding", "political economy", "social protection", "development and diplomacy"],
    blurb: "Development researcher who used to work at J-PAL and as a Fulbright in Colombia, from Nevada; focused on peacebuilding and political economy in Latin America.",
  },
  {
    slug: "alejandro-dominguez",
    email: "alejandro.dominguezcristerna@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Alejandro-Dominguez-1786595796-2.jpg",
    name: "Alejandro Domínguez",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Technology Policy", "AI", "Politics", "Urban Policy"],
    regions: ["Latin America"],
    specifics: ["technology and democratic institutions", "anti-corruption", "urban mobility", "machine learning in policy analysis"],
    blurb: "Public servant who used to work in Nuevo León's Ministry of Education and Congress, from Mexico; focused on technology, democratic institutions, and anti-corruption.",
  },
  {
    slug: "sherab-dorji",
    email: "sherab.dorji@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Sherab-Dorji-1786595815-1.jpg",
    name: "Sherab Dorji",
    program: "MPP in Global Affairs, Class of 2028 (joint MEM)",
    policy: ["Climate", "Energy", "International Development"],
    regions: ["South Asia", "Global South"],
    specifics: ["ecosystem management", "locally led climate adaptation", "clean energy access", "land restoration"],
    blurb: "Climate and clean energy practitioner who has worked in Vietnam, Albania, and the U.S., from Bhutan; focused on locally led adaptation and land restoration.",
  },
  {
    slug: "vaibhav-dutt",
    email: "vaibhav.dutt@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Vaibhav-Dutt-1786595816-1.jpg",
    name: "Vaibhav Dutt",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Urban Policy", "Technology Policy", "Climate"],
    regions: ["South Asia", "Sub-Saharan Africa", "Europe"],
    specifics: ["sustainable urban development", "data governance", "digital rights", "service delivery"],
    blurb: "Lawyer who used to work with the Government of India, from India; focused on sustainable urban development, data governance, and digital rights.",
  },
  {
    slug: "camden-dyer",
    email: "camden.dyer@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Camden-Dyer-1786595807-1.jpg",
    name: "Camden Dyer",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Economics", "International Development", "Social Policy"],
    regions: ["Latin America"],
    specifics: ["political economy", "inclusive economic development", "global labor relations", "unionization"],
    blurb: "Peace Corps volunteer who served in Costa Rica, from New Orleans; focused on political economy and global labor relations.",
  },
  {
    slug: "bryn-evans",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Bryn-Evans-1786595721-1.jpg",
    name: "Bryn Evans",
    program: "MPP in Global Affairs (joint MEM), Class of 2027",
    policy: ["Human Rights", "Climate"],
    regions: ["North America"],
    specifics: ["minority rights", "Indigenous rights", "environmental policy", "culturally inclusive policy"],
    blurb: "Environmental policy advocate from Canada; focused on Indigenous rights and culturally inclusive policy on the Pacific Northwest Coast.",
  },
  {
    slug: "gabriel-falk",
    email: "gabriel.falk@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Gabriel-Falk-1786595798-1.jpg",
    name: "Gabriel Falk",
    program: "MPP in Global Affairs (joint MBA), Class of 2027",
    policy: ["Finance", "International Development", "AI"],
    regions: ["Sub-Saharan Africa"],
    specifics: ["development finance", "blended finance", "AI-assisted investment", "emerging market capital"],
    blurb: "Development finance professional who used to work on governance programs in West Africa, from Ithaca, New York; focused on blended finance and AI-assisted investment.",
  },
  {
    slug: "rafael-gonzalez",
    email: "rafael.gonzalez.reg53@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Rafael-Gonzalez-1786595819.jpg",
    name: "Rafael Gonzalez",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["International Development", "Climate"],
    regions: ["North America"],
    specifics: ["agri-food systems", "economic and societal development"],
    blurb: "Development professional who used to work with the UN, from Vancouver, Canada; focused on agri-food systems and economic development.",
  },
  {
    slug: "liam-graf",
    email: "liam.graf@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Liam-Graf-1786595808-2.jpg",
    name: "Liam Graf",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Technology Policy", "Security", "Foreign Policy"],
    regions: ["Latin America", "North America"],
    specifics: ["emerging technology and national security", "broadband development"],
    blurb: "Peace Corps volunteer who later worked on broadband development in New Mexico and Georgia, from the United States; focused on emerging technology and national security.",
  },
  {
    slug: "arunima-gupta",
    email: "arunima.gupta@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Arunima-Gupta-1786595805.jpg",
    name: "Arunima Gupta",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Climate", "Social Policy"],
    regions: ["South Asia"],
    specifics: ["ESG strategy", "behavioral public policy", "welfare delivery systems", "public-sector innovation"],
    blurb: "Policy consultant who used to work across Delhi NCR, from India; focused on climate, ESG strategy, and welfare delivery.",
  },
  {
    slug: "trisha-gupta",
    email: "trisha.gupta@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Trisha-Gupta-1786595817-1.jpg",
    name: "Trisha Gupta",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Climate", "International Development", "Finance"],
    regions: [],
    specifics: ["climate resilience", "sustainable investing", "global environmental governance", "earth science"],
    blurb: "Climate specialist; focused on climate resilience, sustainable investing, and global environmental governance.",
  },
  {
    slug: "ameya-hadap",
    email: "ameya.hadap@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Ameya-Hadap-1786595797-2.jpg",
    name: "Ameya Hadap",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Energy", "Climate", "Finance", "Security"],
    regions: ["North America"],
    specifics: ["energy transition", "utility regulation", "nuclear energy policy", "cybersecurity", "energy affordability"],
    blurb: "Energy policy analyst from New Jersey; focused on the energy transition, utility regulation, and climate finance.",
  },
  {
    slug: "arshia-haque",
    email: "arshia.haque@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Arshia-Haque-1786595799-1.jpg",
    name: "Arshia Haque",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["International Development", "Finance", "Climate"],
    regions: ["South Asia"],
    specifics: ["inclusive finance", "climate adaptation", "disaster response", "digital payments access"],
    blurb: "Development practitioner who has worked across Nepal, India, and the Maldives, from Bangladesh; focused on inclusive finance, climate adaptation, and disaster response.",
  },
  {
    slug: "ryan-hawkins",
    email: "ryan.hawkins@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Ryan-Hawkins-1786595814-1.jpg",
    name: "Ryan Hawkins",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Security"],
    regions: ["Oceania", "North America"],
    specifics: ["national security", "defense policy", "U.S.–Australia alliance"],
    blurb: "Defense policy specialist; focused on national security and the U.S.–Australia alliance.",
  },
  {
    slug: "axel-herrera-ramos",
    email: "axel.herreraramos@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Axel-Herrera-Ramos-1786595804-1.jpg",
    name: "Axel Herrera Ramos",
    program: "MPP in Global Affairs (joint MBA), Class of 2028",
    policy: ["Climate", "Energy", "Human Rights", "Politics"],
    regions: ["North America", "Latin America"],
    specifics: ["climate displacement", "environmental justice", "immigrant justice", "civic engagement"],
    blurb: "Community organizer who led Latino voter engagement in North Carolina, born in Honduras; focused on climate, environmental justice, and immigrant justice.",
  },
  {
    slug: "jason-hug",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Jason-Hug-1786595617-1.jpg",
    name: "Jason Hug",
    program: "MPP in Global Affairs, Class of 2027 (JD, Yale Law School)",
    policy: ["Security", "Foreign Policy", "Politics"],
    regions: ["Europe", "East Asia", "South Asia"],
    specifics: ["law of armed conflict", "transnational security threats", "U.S.–China relations", "democratic backsliding"],
    blurb: "Security professional who has worked across Germany, Finland, Romania, and Afghanistan; focused on the law of armed conflict and democratic backsliding.",
  },
  {
    slug: "priavi-joshi",
    email: "priavi.joshi@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Priavi-Joshi-1786595818-1.jpg",
    name: "Priavi Joshi",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Politics", "International Development", "Social Policy"],
    regions: ["South Asia"],
    specifics: ["social movements", "participatory democratic governance", "gender and intersectionality", "community-centered development"],
    blurb: "Development researcher who used to work at IDinsight with the Government of India, from India; focused on social movements and participatory governance.",
  },
  {
    slug: "seiyoon-ko",
    email: "seiyoon.ko@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Seiyoon-Ko-1786595816-1.jpg",
    name: "Seiyoon Ko",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["AI", "Technology Policy"],
    regions: ["East Asia"],
    specifics: ["AI governance", "platform regulation", "society and algorithms"],
    blurb: "Technology policy researcher from Seoul, South Korea; focused on AI governance and platform regulation.",
  },
  {
    slug: "andrzej-korlacki",
    email: "andrzej.korlacki@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Andrzej-Korlacki-1786595797.jpg",
    name: "Andrzej Korlacki",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Security"],
    regions: [],
    specifics: [],
    blurb: "Military officer; focus areas not yet listed in his official bio.",
    inferred: true,
  },
  {
    slug: "avia-liberman",
    email: "avia.liberman@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Avia-Liberman-1786595800.jpg",
    name: "Avia Liberman",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Economics", "International Development"],
    regions: ["MENA"],
    specifics: ["fiscal policy", "labor market reform", "trade policy", "post-conflict economic design"],
    blurb: "Economist; focused on fiscal policy, labor market reform, and post-conflict economic design in Israel and Palestine.",
  },
  {
    slug: "metasebiya-ayele-mamo",
    email: "metasebiya.mamo@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Metasebiya-Ayele-Mamo-1786595809-1.jpg",
    name: "Metasebiya Ayele Mamo",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Health"],
    regions: ["Sub-Saharan Africa"],
    specifics: ["global health security", "health equity and access", "pandemic response", "public health systems"],
    blurb: "Public health professional who used to work with Africa CDC and in Botswana, born in Ethiopia; focused on health security and equitable access.",
  },
  {
    slug: "nicola-mcpherson",
    email: "nicola.mcpherson@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Nicola-McPherson-1786595813.jpg",
    name: "Nicola McPherson",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Climate", "Energy", "Economics"],
    regions: ["Oceania"],
    specifics: ["energy sector emissions", "economic incentives for climate action", "public institutions"],
    blurb: "Climate policy specialist who represented Australia at the IPCC, from Australia; focused on energy emissions and economic incentives for climate action.",
  },
  {
    slug: "paige-miles",
    email: "paige.miles@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Paige-Miles-1786595811.jpg",
    name: "Paige Miles",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["International Development", "Economics", "Social Policy"],
    regions: ["South Asia"],
    specifics: ["development economics", "gender equity", "early childhood development"],
    blurb: "Military veteran who deployed to the Western Pacific, from Oklahoma; focused on development economics, gender equity, and early childhood development.",
  },
  {
    slug: "peter-nelson",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Peter-Nelson-1786595636-1.jpg",
    name: "Peter Nelson",
    program: "JD/MPP candidate",
    policy: ["Security", "Politics"],
    regions: ["MENA", "North America"],
    specifics: ["national security", "political advocacy", "election law"],
    blurb: "Veteran who deployed to Iraq in 2020, from Vermont; focused on national security, political advocacy, and election law.",
  },
  {
    slug: "jonas-nepozitek",
    email: "jonas.nepozitek@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Jonas-Nepozitek-1786595801-1.jpg",
    name: "Jonas Nepozitek",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Security", "AI"],
    regions: ["Europe"],
    specifics: ["evidence-based policymaking", "regulatory reform", "data science and AI in public administration"],
    blurb: "Civil servant who used to work at the Czech Office of the Government and Ministry of Finance, from the Czech Republic; focused on national security and AI in public administration.",
  },
  {
    slug: "lena-olszewska",
    email: "lena.olszewska@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Lena-Olszewska-1786595812-2.jpg",
    name: "Lena Olszewska",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Climate", "International Development", "Social Policy", "Health"],
    regions: ["South Asia", "Europe", "Global South"],
    specifics: ["climate mitigation and social outcomes", "health", "employment", "gender equity"],
    blurb: "Development professional who used to work at Plan International in Brussels, with Polish roots; focused on climate mitigation and its social outcomes in India.",
  },
  {
    slug: "hudson-ozello",
    email: "hudson.ozello@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Hudson-Ozello-1786595807-1.jpg",
    name: "Hudson Ozello",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["International Development", "Economics"],
    regions: ["Global South"],
    specifics: ["social enterprise", "poverty alleviation", "public-private partnerships", "public sector operations"],
    blurb: "Peace Corps volunteer who worked in bamboo-industry development; focused on social enterprise and poverty alleviation.",
  },
  {
    slug: "federico-perez",
    email: "federico.perez@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Federico-Perez-1786595803.jpg",
    name: "Federico Pérez",
    program: "MPP in Global Affairs, Class of 2027 (joint MEM)",
    policy: ["Climate"],
    regions: ["Latin America"],
    specifics: ["forest conservation", "climate resilience", "supply chain management"],
    blurb: "Conservation professional who serves on the Latin America board of the Prince Albert II of Monaco Foundation, from Colombia; focused on forest conservation and climate resilience.",
  },
  {
    slug: "pankhuri-prasad",
    email: "pankhuri.prasad@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Pankhuri-Prasad-1786595811-1.jpg",
    name: "Pankhuri Prasad",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Urban Policy", "Economics", "International Development"],
    regions: ["South Asia", "Sub-Saharan Africa", "MENA"],
    specifics: ["urban economic policy", "labor market policy", "cash transfer programs", "economic diversification"],
    blurb: "Economic policy researcher who used to work at the U.S. State Department and the Growth Lab; focused on urban economic policy and labor markets in South Asia.",
  },
  {
    slug: "austin-rose",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Austin-Rose-1786595624-2.jpg",
    name: "Austin Rose",
    program: "MPP in Global Affairs, Class of 2027 (joint JD, Yale Law School)",
    policy: ["Urban Policy", "Economics"],
    regions: ["East Asia", "North America"],
    specifics: ["zoning regulations", "occupational licensing", "municipal water quality", "local government"],
    blurb: "Marine Corps logistics officer who was stationed in Okinawa, Japan; focused on zoning, occupational licensing, and local government.",
  },
  {
    slug: "ana-saenz-de-tejada",
    email: "ana.saenzdetejadagarces@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Ana-Saenz-de-Tejada-1786595795.jpg",
    name: "Ana Sáenz de Tejada",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["International Development", "AI", "Social Policy"],
    regions: ["Latin America"],
    specifics: ["program evaluation", "evidence-based social interventions", "AI ethics in public policy"],
    blurb: "Program evaluator who used to work with UN Women and UNHCR, from Guatemala; focused on evidence-based social interventions and AI ethics in policy.",
  },
  {
    slug: "michael-thompson",
    email: "michael.thompson.mkt44@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Michael-Thompson-1786595814.jpg",
    name: "Michael Thompson",
    program: "MPP in Global Affairs (joint MBA), Class of 2028",
    policy: ["Climate", "International Development", "Finance"],
    regions: ["Sub-Saharan Africa", "Europe"],
    specifics: ["climate innovation", "impact investing", "frontier markets", "systems investing"],
    blurb: "Impact investor who has worked across Kenya, Senegal, Nigeria, and the UK, from Ghana; focused on climate innovation and frontier markets.",
  },
  {
    slug: "chang-tu",
    email: "chang.tu@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Chang-Tu-1786595801.jpg",
    name: "Chang Tu",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Finance", "Economics"],
    regions: ["Southeast Asia"],
    specifics: ["financial stability", "inclusive financial systems", "emerging economies"],
    blurb: "Finance professional from Singapore; focused on financial stability and inclusive financial systems in Southeast Asia.",
  },
  {
    slug: "cheney-wen",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Cheney-Wen-1786595735-1.jpg",
    name: "Cheney Wen",
    program: "JD/MPP dual candidate, Class of 2028",
    policy: ["Security", "Foreign Policy"],
    regions: ["East Asia", "North America"],
    specifics: ["Taiwan–U.S.–China relations", "American grand strategy", "national security law", "international law"],
    blurb: "Law student at Yale Law School, from Taiwan; focused on Taiwan–U.S.–China relations and national security law.",
  },
  {
    slug: "isaiah-williams",
    email: "isaiah.williams@yale.edu",
    photo: "https://jackson.yale.edu/wp-content/uploads/2026/08/Isaiah-Williams-1786595806-1.jpg",
    name: "Isaiah Williams",
    program: "MPP in Global Affairs, Class of 2027",
    policy: ["Climate", "International Development"],
    regions: ["Latin America", "North America"],
    specifics: ["regenerative agriculture", "environmental justice", "food system resilience", "nature-based solutions"],
    blurb: "Engineer who served in the Peace Corps in Panama, from the United States; focused on regenerative agriculture and environmental justice.",
  },
];
